kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./dockerfiles/Dockerfile
  context: .

spec:
  operator: tf
  image: image
  command: ""

  tensorboard:
    enabled: true

  types:
    Worker:
      count: 1
      resources:
        cpus: 3
        ramRatio: 2
        shmSizeGB: 0
        accelerators: # optional
          gpu:
            count: 0
            type: gpu
            product: nvidia-tesla-t4
